### ISSUE TITLE
Global sign in review notes

### ISSUE THREAD

**Issue by TheWilks** [karacampbell/daaas#13]
- [x] General note - Be consistent across all pages in terms of code (padding, margin, all that) just to make things easier for devs to use patters for future work. 
- [x] 4px radius on the card or paper
- [x] Field text 14px field height should remain 40px
- [x] Icon button hit area should be 40px (padding 8px instead of 12px)
-- Things to consider… ".MuiIconButton-edgeEnd" may be effected. If it is and is not dynamically changed it would need to go from -12px to -8px. Just be aware of what will be effected by this change and we can discuss if it blows things up. Icon buttons in text fields should change as well.
- [x] Fix the spacing on the icons button in the footer. 
![image](https://user-images.githubusercontent.com/6516828/81632963-8a8e7680-93d9-11ea-8a26-bc05cb540b30.png)
- [x] The password fields seem a little off compared to the other fields you will see my comments on each individual page. Let's stay consistent.
- [x] Buttons and checkboxes not acting as the default material ui. For example when something is clicked it stays in a hover state and the click animation has been removed. If this is due to trying to fix the tabbing issue that was brought up I would revert the change and keep working on it. Ideally everything stays the same except when a user tabs to a button it displays as if it’s a hover. 
- [x] Bring all content margin in 8px on the right and left but leave the hr at the current width.
![image](https://user-images.githubusercontent.com/6516828/81632994-9ed27380-93d9-11ea-9eda-464f7280abda.png)
- [x] It might be worth investigating changing default text size to 14px but review all changes I am requesting first

**Comment by karacampbell** [comment]
@TheWilks hey! I can look into overwriting the font sizes when I'm done with button focus stuff ... what size would you like each of these to be? Or are we just going to change body1 to 14? This is what they are by default:
'h1' - 96px light
'h2' - 60px light
'h3' - 48px regular
'h4' - 34px regular
'h5' - 24px regular
'h6' - 20px medium
'subtitle1' - 16px regular
'subtitle2' - 14px medium
'body1' - 16px regular
'body2' - 14px regular
'caption' - 12px regular
'button' - 14px medium
'overline' - 12px regular (uppercase)

Currently we are just using the styles that match what you want and putting that class on the text, so for example on the login we are putting the h6 class on the h1 and the body2 class on the paragraph text. So if we overwrite the body text globally I think we should do the rest too. What do you think?

**Comment by TheWilks** [comment]
@karacampbell I am fine with adding classes. I was hoping you guys could shine some light on the best approach to take. Is adding of these classes hindering your work in anyway?
