### ISSUE TITLE
Cross browser testing

### ISSUE THREAD

**Issue by karacampbell** [karacampbell/daaas#2]

**Comment by haze0028** [comment]
- [ ] IE 'Home' - Search analysis header/dropdown overlap
- [ ] IE 'Home' - Articles squished  
- [ ] IE 'Visualizations' - Sign up squished
- [ ] All browsers 'Content' - Additional formats list
- [ ] All browsers - 'Documentation' - Additional formats list
- [ ] IE 'Documentation' - Sign up squished
- [ ] IE 'Projects' - Drawer open causes blank screen
- [ ] IE 'Sign-in - panel not centered

- Index results links broken
- [ ]     - Confidential table
- [ ]     - Public table

**Comment by haze0028** [comment]
![allbrowsers - content](https://user-images.githubusercontent.com/16760818/82844603-1a8af080-9eaf-11ea-8c91-df21a81cd921.jpg)
![ie - documentation1](https://user-images.githubusercontent.com/16760818/82844604-1b238700-9eaf-11ea-96bd-75c68e9e40f1.jpg)
![ie - home](https://user-images.githubusercontent.com/16760818/82844605-1b238700-9eaf-11ea-8437-0fc1fa69665b.jpg)
![ie - home2](https://user-images.githubusercontent.com/16760818/82844606-1b238700-9eaf-11ea-8572-0f0c2f5b2a57.jpg)
![ie - projects1](https://user-images.githubusercontent.com/16760818/82844608-1bbc1d80-9eaf-11ea-8897-8ad3a34e396b.jpg)
![ie - signin1](https://user-images.githubusercontent.com/16760818/82844609-1bbc1d80-9eaf-11ea-8ae9-0c133d9f4e30.jpg)
![ie - vis1](https://user-images.githubusercontent.com/16760818/82844610-1bbc1d80-9eaf-11ea-820e-65f49eab1cbd.jpg)

**Comment by haze0028** [comment]
Seperated into individual issues
