### ISSUE TITLE
Sign in screen - Keep me signed in / Forgot password row margin fix / Label shrink size to .0857

### ISSUE THREAD

**Issue by TheWilks** [karacampbell/daaas#24]
Due to the hit area on the checkbox the top and bottom margin of the row should be 16px instead of 24px to keep spacing consistent. This may impact mobile spacing if things stack so ill leave it to you guys to find the best solution. The general rule will be 24px spacing but we will need to account for hit areas in some cases. I'll also do a mobile review at some point.

![Capture](https://user-images.githubusercontent.com/6516828/82489311-702a5c00-9aaf-11ea-91b4-a71dcd718dfb.PNG)

**Comment by TheWilks** [comment]
Here is the code I changed in the browser FYI...

MuiInputLabel-outlined.MuiInputLabel-shrink {
    transform: translate(14px, -6px) scale(0.857);
}

**Comment by haze0028** [comment]
Made the two changes. Want me to close this, or leave it open until we get mobile styles?

**Comment by TheWilks** [comment]
Good to close. I’ll do a mobile review next week.
