### ISSUE TITLE
Icon button padding fix

### ISSUE THREAD

**Issue by TheWilks** [karacampbell/daaas#28]
This was a previous request must have gotten over written or something. Ignore if the change just has not been pushed yet.

Icon button hit area should be 40px (padding 8px instead of 12px)

Things to consider… ".MuiIconButton-edgeEnd" may be effected. If it is and is not dynamically changed it would need to go from -12px to -8px. Just be aware of what will be effected by this change and we can discuss if it blows things up. Icon buttons in text fields should change as well.

**Comment by karacampbell** [comment]
@TheWilks Yeah this was done.... we had a little git mishap yesterday. We'll look into getting it back
