### ISSUE TITLE
Cross browser - IE 'Home' - Articles squished

### ISSUE THREAD

**Issue by haze0028** [karacampbell/daaas#33]
![ie - home2](https://user-images.githubusercontent.com/16760818/82916286-d8f65600-9f3f-11ea-9ba7-bb02bbda085e.jpg)

**Comment by karacampbell** [comment]
Can we fix this on this ticket too: 
- scroll bar showing in Edge 
![image](https://user-images.githubusercontent.com/41926868/82918140-4d31f900-9f42-11ea-8342-d9eb8b0b6186.png)
