### ISSUE TITLE
Mobile review - Minor spacing fixes

### ISSUE THREAD

**Issue by TheWilks** [karacampbell/daaas#45]
- [x] SM to XL screen size add 48px of margin the top and make the padding after the Canada logo 48px. XS screen size has 24px top and bottom and that is perfect.

![Capture](https://user-images.githubusercontent.com/6516828/83553538-51798b80-a4d9-11ea-9edf-b5dd44a67c54.PNG)

- [x] SM to XL screen give paper left/right padding of 40px since we indented the content 8px.

- [x] XS screen give paper left/right padding 16px since we indented the content 8px.

**Comment by TheWilks** [comment]
So I think this was just bad communication on my part. All the changes seem correct except the changes were not applied to the XL screen size I may have missed a size if there is a XXL screens size. Basically everything above XS.

**Comment by haze0028** [comment]
changes are live
