### ISSUE TITLE
Sign in - Change "Back to sign in" to "Sign in instead"

### ISSUE THREAD

**Issue by TheWilks** [karacampbell/daaas#48]
Change "Back to sign in" to "Sign in instead" on all pages. I got a bit of feedback and I think its unclear what "Back to sign in" means. The user may not understand that "Back to sign in" means that their current task is being cancelled.

**Comment by haze0028** [comment]
Changed

**Comment by TheWilks** [comment]
The button should say "Sign in instead" not "Sign in"

**Comment by haze0028** [comment]
Sorry, updated the text

**Comment by haze0028** [comment]
changes are live
